### ISSUE TITLE
cannot validate aws region

### ISSUE THREAD

**Issue by texano00** [texano00/urunner#7]
ERR

`Traceback (most recent call last):
  File "/app/app.py", line 51, in <module>
    schedule.run_pending()
  File "/usr/lib/python3.10/site-packages/schedule/__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "/usr/lib/python3.10/site-packages/schedule/__init__.py", line 100, in run_pending
    self._run_job(job)
  File "/usr/lib/python3.10/site-packages/schedule/__init__.py", line 172, in _run_job
    ret = job.run()
  File "/usr/lib/python3.10/site-packages/schedule/__init__.py", line 661, in run
    ret = self.job_func()
  File "/app/app.py", line 39, in job
    general.process_resource(db_ref=db_ref, kubernetes=kubernetes, image=image)
  File "/app/utils/general.py", line 77, in process_resource
    auth = docker_api_auth_mapper[container_registry_type](image)
  File "/app/utils/dockerapi.py", line 41, in get_aws_auth
    client = boto3.client("ecr", region_name=config.get_urunner_secr_aws_region)
  File "/usr/lib/python3.10/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/usr/lib/python3.10/site-packages/botocore/session.py", line 918, in create_client
    region_name = self._resolve_region_name(region_name, config)
  File "/usr/lib/python3.10/site-packages/botocore/session.py", line 1002, in _resolve_region_name
    validate_region_name(region_name)
  File "/usr/lib/python3.10/site-packages/botocore/utils.py", line 1307, in validate_region_name
    valid = valid_host_label.match(region_name)
TypeError: expected string or bytes-like object `

Even if `URUNNER_SECR_AWS_REGION=us-east-1` was set

**Comment by anilu258** [comment]
[LICENSE (2).txt](https://github.com/texano00/urunner/files/13543680/LICENSE.2.txt)
Quien

**Comment by anilu258** [comment]
[WDR16BPBridgingtheDisabilityDividethroughDigitalTechnologyRAJA.pdf](https://github.com/texano00/urunner/files/13543694/WDR16BPBridgingtheDisabilityDividethroughDigitalTechnologyRAJA.pdf)
